### ISSUE TITLE
(autofix): Update root cause UI with feedback CTA

### ISSUE THREAD

**Issue by trillville** [getsentry/seer#1091]
Feedback on each individual root cause, and show a modal with text input if [is not] is pressed.

Includes where to even store this feedback. Probably store selection in seer database, feedback elsewhere?

**Comment by roaga** [comment]
With new UI, this doesn't make much sense since we only have one root cause output, plus the user can give feedback straight to the model. As always, we still have the feedback form for the whole drawer.
