### ISSUE TITLE
(autofix) Investigate incorrect diff fixer slowness

### ISSUE THREAD

**Issue by trillville** [getsentry/seer#1358]

**Comment by roaga** [comment]
![Image](https://github.com/user-attachments/assets/7ea906fd-f622-456f-a10d-1bb020aa564d)

Seems to me that the big source of slow down (besides LLM calls) is the GitHub API.
We also have this recurring 100ms missing instrumentation throughout all of Autofix, which adds up. Probably just code execution.

**Comment by roaga** [comment]
![Image](https://github.com/user-attachments/assets/726fc47a-d1ec-4bab-a16c-9f89e9c768c1)
I think that optimization could help this really slow code too.

**Comment by roaga** [comment]
Try the RapidFuzz library
