### ISSUE TITLE
(autofix) Nicer errors on the UI

### ISSUE THREAD

**Issue by ram-senth** [getsentry/seer#1403]
We can pass errors through a cheap llm call to make them look nicer and not like ![Image](https://github.com/user-attachments/assets/d344b71f-6a99-435f-b762-3db00cf4a8e4)

**Comment by roaga** [comment]
Maybe it would be better to just hardcode some messages? In the example above, even if we made it more readable, it's an internal issue and we probably wouldn't want to explain it to the user anyway--we'd just say "Autofix had an internal error."
