### ISSUE TITLE
Audit and improve agent prompts

### ISSUE THREAD

**Issue by jennmueng** [getsentry/seer#215]
We haven't spent much time prompt engineering each of our current prompts. We often see flaky issues with the agents such as
- Forgetting that they have tools to use
- Responding with invalid characters in the response (both JSON and XML outputs)

Take a closer look at how we prompt & parse LLM input/output and make it more robust.

**Comment by lgrammel** [comment]
I have added a section on prompting focussed on those 2 problems based on my own experience (since those are common problems).

Are there any specific runs that you want me to look at?

I cannot move this ticket, but it should be in progress now.
