### ISSUE TITLE
(autofix): Support interactive Q&A flow

### ISSUE THREAD

**Issue by trillville** [getsentry/seer#450]
Support for an interactive UX flow involving questions and user answers

![Image](https://github.com/getsentry/seer/assets/8632090/9a56915c-53f7-4ca4-a687-a565115e9ad3)

**Comment by roaga** [comment]
# Core Steps to Implement

1. Tool call for Q&A feedback, with frontend for user to respond
2. Tool call for Q&A context, with frontend for user to respond
3. Always-present input box for user to interrupt with any message, added to its memory
4. Direct editing support for outputs, that send updated content back to model to replace its memory
5. Work with designer/frontend people to communicate the same info we already do, just not as a wall of text

Research doc: https://www.notion.so/sentry/Creative-Wand-Autofix-568dc4e1f967458288bc1cef40234610?pvs=4
